# 1. LIBRERÍAS ---------------------------------------------------------------
library(ggplot2)
library(ggfortify)
library(aTSA)
library(nortest)
library(moments)
library(fitdistrplus)
library(MASS)
library(tseries)
library(tsoutliers)
library(forecast)
library(expsmooth)
library(fma)
library(FinTS)
library(rugarch)
library(scales)
library(ggpubr)
